/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  buildPostProcessor: () => buildPostProcessor,
  default: () => BlurPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var DEFAULT_SETTINGS = {
  revealOnHover: false
};
var BlurWidget = class extends import_view.WidgetType {
  constructor(content, type) {
    super();
    this.content = content;
    this.type = type;
  }
  toDOM() {
    const span = createSpan({ cls: `blur-widget blur-widget-${this.type}` });
    const code = span.createEl("code", { cls: this.getCssClass() });
    code.setText(this.type === "brick" ? this.content.replace(/[^\s]/g, "\u2588") : this.content);
    return span;
  }
  getCssClass() {
    switch (this.type) {
      case "blur":
        return "blur-inline";
      case "brick":
        return "blur-brick";
      case "bone":
        return "blur-bone";
    }
  }
  eq(other) {
    return other.content === this.content && other.type === this.type;
  }
  ignoreEvent() {
    return false;
  }
};
var BLUR_REGEXP = /(`~\{.*?\}`|`~\[.*?\]`|`~\(.*?\)`)/gm;
var viewPlugin = import_view.ViewPlugin.fromClass(class {
  constructor(view) {
    this.decorations = this.buildDecorations(view);
  }
  update(update) {
    const livePreviewChanged = update.state.field(import_obsidian.editorLivePreviewField) !== update.startState.field(import_obsidian.editorLivePreviewField);
    if (update.docChanged || update.selectionSet || update.viewportChanged || livePreviewChanged) {
      this.decorations = this.buildDecorations(update.view);
    }
  }
  destroy() {
  }
  buildDecorations(view) {
    if (!view.state.field(import_obsidian.editorLivePreviewField)) {
      return import_view.Decoration.none;
    }
    const builder = new import_state.RangeSetBuilder();
    const currentSelections = [...view.state.selection.ranges];
    for (const range of view.visibleRanges) {
      const firstLine = view.state.doc.lineAt(range.from).number;
      const lastLine = view.state.doc.lineAt(range.to).number;
      for (let n = firstLine; n <= lastLine; n++) {
        const line = view.state.doc.line(n);
        const matches = Array.from(line.text.matchAll(BLUR_REGEXP));
        for (const match of matches) {
          let add = true;
          const from = match.index != void 0 ? match.index + line.from : -1;
          const to = from + match[0].length;
          if (to - from < 5) {
            add = false;
          }
          currentSelections.forEach((r) => {
            if (r.to >= from && r.from <= to) {
              add = false;
            }
          });
          if (add) {
            const text = match[0];
            let type;
            let content;
            if (text.startsWith("`~{") && text.endsWith("}`")) {
              type = "blur";
              content = text.slice(3, -2);
            } else if (text.startsWith("`~[") && text.endsWith("]`")) {
              type = "brick";
              content = text.slice(3, -2);
            } else {
              type = "bone";
              content = text.slice(3, -2);
            }
            builder.add(from, to, import_view.Decoration.replace({ widget: new BlurWidget(content, type), inclusive: true }));
          }
        }
      }
    }
    return builder.finish();
  }
}, {
  decorations: (v) => v.decorations
});
var BlurPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new BlurSettingTab(this.app, this));
    this.applyHoverClass();
    this.registerEvent(this.app.workspace.on("window-open", (_leaf, win) => {
      if (this.settings.revealOnHover) {
        win.document.body.addClass("obsidian-blur-hover");
      }
    }));
    this.registerMarkdownCodeBlockProcessor("blur", (source, el, ctx) => this.blurBlockHandler(source, el, ctx));
    this.registerMarkdownCodeBlockProcessor("blur-brick", (source, el, ctx) => this.blurBlockHandler(source, el, ctx));
    this.registerMarkdownCodeBlockProcessor("blur-bone", (source, el, ctx) => this.blurBlockHandler(source, el, ctx));
    this.registerMarkdownPostProcessor(
      buildPostProcessor()
    );
    this.registerEditorExtension(viewPlugin);
  }
  onunload() {
    for (const doc of this.getDocuments()) {
      doc.body.removeClass("obsidian-blur-hover");
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /** Every document the workspace occupies: the main window plus any popouts. */
  getDocuments() {
    const docs = /* @__PURE__ */ new Set([this.app.workspace.containerEl.ownerDocument]);
    this.app.workspace.iterateAllLeaves((leaf) => {
      docs.add(leaf.view.containerEl.ownerDocument);
    });
    return Array.from(docs);
  }
  applyHoverClass() {
    for (const doc of this.getDocuments()) {
      if (this.settings.revealOnHover) {
        doc.body.addClass("obsidian-blur-hover");
      } else {
        doc.body.removeClass("obsidian-blur-hover");
      }
    }
  }
  /**
   * Render one <code> per whitespace-separated token, wrapping each source
   * line in its own div.
   *
   * The tokens were previously produced by source.split(/\W+/), which splits
   * on every non-word character and therefore discarded every apostrophe,
   * hyphen, colon and bracket in the source. "Don't tell: 555-1234" came back
   * as five bare words, so revealing the text showed something the user never
   * wrote. Splitting on /\s+/ keeps punctuation attached to its token.
   */
  renderBlock(el, blockCls, innerCls, codeCls, source, brick) {
    const block = el.createDiv({ cls: blockCls });
    const inputElement = block.createDiv({ cls: innerCls });
    for (const line of source.replace(/\n$/, "").split("\n")) {
      const lineEl = inputElement.createDiv({ cls: "blur-block-line" });
      for (const token of line.split(/\s+/)) {
        if (token === "") continue;
        lineEl.createEl("code", { text: brick ? token.replace(/[^\s]/g, "\u2588") : token, cls: codeCls });
      }
    }
  }
  blurBlockHandler(source, el, _ctx) {
    if (el.className === "block-language-blur-brick") {
      this.renderBlock(el, "blur-brick-block", "blur-brick-innerblock", "blur-brick", source, true);
    } else if (el.className === "block-language-blur-bone") {
      this.renderBlock(el, "blur-bone-block", "blur-bone-innerblock", "blur-bone", source, false);
    } else if (el.className === "block-language-blur") {
      this.renderBlock(el, "blur-block", "blur-innerblock", "blur-inline", source, false);
    }
  }
};
function buildPostProcessor() {
  return (el) => {
    el.findAll("code").forEach((code) => {
      var _a;
      if (((_a = code.parentElement) == null ? void 0 : _a.tagName) === "PRE") return;
      const text = code.innerText.trim();
      if (text.startsWith("~[") && text.endsWith("]")) {
        const content = text.slice(2, -1);
        code.addClass("blur-brick");
        code.innerText = content.replace(/[^\s]/g, "\u2588");
      } else if (text.startsWith("~(") && text.endsWith(")")) {
        const content = text.slice(2, -1);
        code.addClass("blur-bone");
        code.innerText = content;
      } else if (text.startsWith("~{") && text.endsWith("}")) {
        const content = text.slice(2, -1);
        code.addClass("blur-inline");
        code.innerText = content;
      }
    });
  };
}
var BlurSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [
      {
        name: "Reveal on hover",
        desc: "Reveal obfuscated text when hovering with the mouse.",
        render: (setting) => {
          setting.addToggle((toggle) => toggle.setValue(this.plugin.settings.revealOnHover).onChange(async (value) => {
            this.plugin.settings.revealOnHover = value;
            await this.plugin.saveSettings();
            this.plugin.applyHoverClass();
          }));
        }
      }
    ];
  }
};

/* nosourcemap */